version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - database
            - redis
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3307:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            #- MYSQL_USER=${DB_USERNAME} will create normal user and use this for prod
            #- MYSQL_PASSWORD=${DB_USERNAME} will create normal user and use this for prod
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        #command: --default-authentication-plugin=mysql_native_password --ssl=0 #Force MySQL to run without SSL
        volumes:
            - db-data:/var/lib/mysql
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379
volumes:
    db-data: ~
